// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-WeOEePgLcfhuy8IHYrtMq-xGm5Jzzd0',
    appId: '1:856465934662:web:7ad636a5f7da69553bfd47',
    messagingSenderId: '856465934662',
    projectId: 'jctapp-67571',
    authDomain: 'jctapp-67571.firebaseapp.com',
    storageBucket: 'jctapp-67571.appspot.com',
    measurementId: 'G-E4BEHRNHMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDemus1uhB9tvzSntQDnC0U8yiZOIbJfQ',
    appId: '1:856465934662:android:30b1663d4be77ea03bfd47',
    messagingSenderId: '856465934662',
    projectId: 'jctapp-67571',
    storageBucket: 'jctapp-67571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgMjHPLAxDm23WTV0RrOX4SjvlMlhwHI',
    appId: '1:856465934662:ios:77b13da94f9c3c5c3bfd47',
    messagingSenderId: '856465934662',
    projectId: 'jctapp-67571',
    storageBucket: 'jctapp-67571.appspot.com',
    iosBundleId: 'com.example.jct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqgMjHPLAxDm23WTV0RrOX4SjvlMlhwHI',
    appId: '1:856465934662:ios:77b13da94f9c3c5c3bfd47',
    messagingSenderId: '856465934662',
    projectId: 'jctapp-67571',
    storageBucket: 'jctapp-67571.appspot.com',
    iosBundleId: 'com.example.jct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-WeOEePgLcfhuy8IHYrtMq-xGm5Jzzd0',
    appId: '1:856465934662:web:ea198b065d4287f43bfd47',
    messagingSenderId: '856465934662',
    projectId: 'jctapp-67571',
    authDomain: 'jctapp-67571.firebaseapp.com',
    storageBucket: 'jctapp-67571.appspot.com',
    measurementId: 'G-H5ZDVS6ELP',
  );
}
